name: Development Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, edited, reopened]
jobs:
  backend_deployment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: lint
        run: npm run lint
      - name: Prettier check
        run: npm run format
      - name: Deploy Backend to render
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ' '), '#skip') == false }}
        uses: johnbeynon/render-deploy-action@v0.0.8
        with: 
          service-id: ${{ secrets.API_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
      - name: Notify Discord on success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: Backend Deployment
          text: Phone book Backend successfully deployed
          description: Deployment to Render successful
      - name: Notify Discord on failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: Backend Deployment
          text: Phone book Backend deployment failed
          description: Deployment to Render failed chcck logs for more details
  frontend_deployment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Build Frontend
        working-directory: ./client
        run: npm install
      - name: Build Frontend
        working-directory: ./client
        run: npm run build
      - name: Deploy Front end to render
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ' '), '#skip') == false }}
        uses: johnbeynon/render-deploy-action@v0.0.8
        with: 
          service-id: ${{ secrets.CLIENT_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
      - name: Notify Discord on success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: Frontend Deployment
          text: Phone book Frontend successfully deployed
          description: Deployment to Render successful
      - name: Notify Discord on failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: Frontend Deployment
          text: Phone book Frontend deployment failed
          description: Deployment to Render failed chcck logs for more details
  tag_release:
    needs: [frontend_deployment, backend_deployment]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18" 
      - name: Bump version and push tag to repo
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ' '), '#skip') == false }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch